### PR TITLE
Add `--access` option

### LINKED ISSUE #55: Detect File Read
Hey, I'm looking for a way to monitor file access not modification.

Is there a way to monitor when a file is being read?

Thanks.

### PR DESCRIPTION
**Pull request by AlexWayfer**
This option allows the command (or block of code) be executed when watching files were accessed (readed).

Resolve #55

### CODE REVIEW

**Comment by thomasfl** [comment]
Is there any performance penalty detecting file read events?

Another problem may be Windows, where storing files last access time is turned off by default to speed up the system:

```
Some systems also provide options to disable access time updating altogether. In Windows, starting with Vista, file access time updating is disabled by default.[6]
```
Source: https://en.wikipedia.org/wiki/MAC_times

The functionality is really cool, since not all filewatchers have it. The Readme file should have a section that tells that that for Windows users, storing files last access time have to be turned on. 

Consider renaming the -access option --detect-filereads.

**Comment by AlexWayfer** [comment]
> Is there any performance penalty detecting file read events?

Insignificant.

> Another problem may be Windows, where storing files last access time is turned off by default to speed up the system:

Yes, as I wrote [here](https://github.com/thomasfl/filewatcher/issues/55#issuecomment-310889250).

> The functionality is really cool, since not all filewatchers have it. The Readme file should have a section that tells that that for Windows users, storing files last access time have to be turned on.

But what about:

> Having no platform specific code or native C code, is what makes filewatcher robust. Maybe this feature could be published as a separate gem that monkeypatches or extends filewatcher?

([source](https://github.com/thomasfl/filewatcher/issues/55#issuecomment-310898618))

?

> Consider renaming the -access option --detect-filereads.

Why? It's longer, and even in Windows this event calls `access`, doesn't it?

**Comment by thomasfl** [comment]
Yes, I remember now. I guess this feature probably is of interest only for a few unix and mac developers.

**Comment by AlexWayfer** [comment]
Suppressed by external plugin (still doesn't work in Windows due to NTFS restrictions): https://github.com/filewatcher/filewatcher-access

Let's switch to Filewatcher v2 flexible ecosystem!

**Pull request closed without merging**
